### ISSUE TITLE
selecting item

### ISSUE THREAD

**Issue by papertigers** [iluuu1994/ITSidebar#1]
You mention in your readme a method that doesn't seem to exist: 

link@iria ~/src/ITSidebar (git)-[master] % grep -Hnr "selectItemAtIndex" .
./README.md:52: - (void)selectItemAtIndex:(int)index;

Meant for the user to implement or just out of date documentation.

**Comment by iluuu1994** [comment]
Of course you're right.

You can use the property `itemAtIndex`.
So just call `setSelectedIndex:` on the sidebar.

**Comment by iluuu1994** [comment]
Updated the readme.

Thanks!
