### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by ghost** [iluuu1994/ITSidebar#3]
I created a project from scratch, added your classes, made the window as in your example, added the images, but when I run it no images are shown in the sidebar. The sidebar is just gray.. Any idea what could cause this? 

Thanks.

**Comment by iluuu1994** [comment]
The sidebar does not add any items on itself. This is the job of the controller.

Take a look at the `ITAppDelegate` class:

``` objc
[self.sidebar addItemWithImage:[NSImage imageNamed:@"imageName"] 
    alternateImage:[NSImage imageNamed:@"imageName-pushed"] 
    target:self action:@selector(whatever:)];
```

This is what really adds the item to the sidebar.

**Comment by ghost** [comment]
Yes, I did add this, just like in the example project. (and yes, everything is linked up correctly).

**Comment by iluuu1994** [comment]
Well, there's not enough information for me to help you. Is the code actually executed? Try doing a `NSLog(@"%@", self.sidebar)` before the `addItem...` call.

**Comment by ghost** [comment]
That's executing for sure. I have made a sample project showing the issue. hoping you can help.. Download here: https://copy.com/B4YsCFkW6wuO

Thanks!

**Comment by iluuu1994** [comment]
@wesleyh You did not connect the `IBOutlet` in Interface Builder.

![screen shot 2014-01-19 at 13 29 28](https://f.cloud.github.com/assets/1752683/1949448/6792f4a0-8105-11e3-9f0a-205d770b058e.png)
