### ISSUE TITLE
Resizing - Icons out of view

### ISSUE THREAD

**Issue by ghost** [iluuu1994/ITSidebar#4]
Is it possible to add some sort of constraint so that the icons are never out of view and always in the top? I see even in your own demo that when you resize the icons are sort of 1/3rd from the top and can also become out of view.

**Comment by iluuu1994** [comment]
That's what the scroll view is for.

**Comment by ghost** [comment]
Thanks for your fast response but that doesn't really help me :-) - What setting do I need to change for the sidebar icons to be fixed in place no matter how it's resized?

**Comment by iluuu1994** [comment]
You need to look into `NSLayoutConstraint`s and Auto Layout. 

Please be more specific about what you want exactly.

**Comment by ghost** [comment]
thanks, that solved it..
